name: covid_19_app
description: Flutter app for manage COVID-19 hospital.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.1-alpha0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+4
  provider: ^3.1.0
  flutter_spinkit: ^4.0.0
  flutter_dialogflow: ^0.1.3
  bubble: ^1.1.9+1
  flutter_svg: ^0.18.0
  country_code_picker: ^1.4.0
  toast: ^0.1.5
  url_launcher: ^5.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/eli-osjukx-f28e600af05e.json
    - assets/woman.jpg
    - assets/home_hospital.gif
    - assets/home.gif
    - assets/loading.gif
    - assets/background_home.png
    - assets/icons/admin/asignar_pacientes.svg
    - assets/icons/admin/conceder_roles.svg
    - assets/icons/paciente/protocolo.svg
    - assets/icons/paciente/riesgo_aislamiento.svg
    - assets/icons/prof_salud/mis_pacientes.svg
    - assets/icons/chat.svg
    - assets/icons/chequeo_diario.svg
    - assets/icons/info.svg
    - assets/icons/mi_perfil.svg
    - assets/design_icons/alcohol_70.png
    - assets/design_icons/alcohol_glicerinado.png
    - assets/design_icons/desinfectante.png
    - assets/design_icons/jabon.png
    - assets/bot.png
    - assets/user.png
    - assets/limpieza_y_desinfeccion.json
    - assets/en_casa.json
    - assets/emocionometro/girl_1/abrumado.png
    - assets/emocionometro/girl_1/ansioso.png
    - assets/emocionometro/girl_1/aterrado.png
    - assets/emocionometro/girl_1/bien.png
    - assets/emocionometro/girl_1/enojado.png
    - assets/emocionometro/girl_1/feliz.png
    - assets/emocionometro/girl_1/impotente.png
    - assets/emocionometro/girl_1/muy_mal.png
    - assets/emocionometro/girl_1/normal.png
    - assets/emocionometro/girl_1/triste.png

    - assets/emocionometro/emociones/abrumado.json
    - assets/emocionometro/emociones/aterrado.json
    - assets/emocionometro/emociones/muy_mal.json
    - assets/emocionometro/emociones/enojado.json
    - assets/emocionometro/emociones/triste.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: Lato
      fonts:
        - asset: assets/Lato-Regular.ttf
        - asset: assets/Lato-Bold.ttf
    - family: Hind
      fonts:
        - asset: assets/Hind-SemiBold.ttf
